### ISSUE TITLE
[M0] Pagos

### ISSUE THREAD

**Issue by alvarogaro** [marcosrmartin/PerroAndaluz#11]
Buenas de nuevo @marcosrmartin, al igual que te he comentado en el issue #10, me gustaría también que me dieras algunas directrices respecto a que quieres almacenar en la Clase Usuario y Pago. Con este issue busco básicamente tener una idea clara de como quieres estructurar las clases y que quieres guardar en ellas ya que luego será importante para las fases posteriores.

**Comment by marcosrmartin** [comment]
Pues para la clase *Usuario*:
- Nombre
- Correo
- Lista de eventos

En cuanto a la clase *Pago*:
- Nombre.
- Fecha del pago.
- Precio.
- Quien ha pagado.
- Quien ha participado.
- *Categoría*
- *Foto*

Las dos últimas podrían prescindirse en la implementación, pero como idea ahí está. Al igual que en el #10, si ves que se podría modificar o añadir algún atributo lo hablamos.

**Comment by alvarogaro** [comment]
buenas @marcosrmartin, centrándome primero en estas clases como me has comentado antes, te comento: 
1º Respecto a los usuarios que participan dentro de la clase pago, es necesario que el usuario que realiza el pago este dentro de los que participan o simplemente se refleja solo en el atributo de quien ha pagado?? 
2º Que comprobaciones crees que serían importantes de implementar en estas clases ??
3º Respecto a los constructores, prefieres que cuando se inicialice un objeto se haga con todos sus atributos o que se haga con algunos en concreto y luego se añadan otros posteriormente con el uso de Set's??

**Comment by marcosrmartin** [comment]
Buenas Álvaro, respondiendo a tus dudas:
1º El que paga tiene que estar en los que participa si ha participado, es decir, porque alguien realice un pago no implica que este participe en el mismo, yo puedo pagar un gasto si alguien no tiene dinero y no participar en este.
2º Que se puedan seleccionar solo los participantes que están en evento, aparte no veo ninguna más allá de comprobar los tipos y si existen variables.
3º Esto no se si serían comprobaciones, pero como tú preguntas, ambos necesitan iniciarse con un nombre, en cuanto a *Pago* este necesita también la fecha, quien ha pagado y mínimo un participante en el pago.

**Comment by alvarogaro** [comment]
Buenas @marcosrmartin, voy a modificar un poco los issues porque he estado hablando con JJ y me ha dicho que tengo que remodelar un poco el planteamiento del objetivo.

**Comment by alvarogaro** [comment]
Respecto a los Pagos, he pensado en realizarlos como objeto-valor ya que realmente cuando realizamos un pago, este pago quedaría inmutable. Como idea principal para  satisfacer a #2 creo que sería suficiente
