### ISSUE TITLE
[M0] Lenguaje de Programación  🕵️‍♂️

### ISSUE THREAD

**Issue by alvarogaro** [marcosrmartin/PerroAndaluz#8]
Buenas Marcos, 

Voy a trabajar sobre tu repositorio, abro este issue para que me comentes que lenguaje has pensado para la programación del proyecto, también si tienes alguna concreción respecto a alguna práctica sobre este lenguaje puedes comentármelo 🤑

**Comment by marcosrmartin** [comment]
Hola Álvaro, había pensado en utilizar Node.js ya que para este problema no se necesita mucha capacidad de cómputo; además  este lenguaje tiene su propio entorno de desarrollo.
