### ISSUE TITLE
[M0] Propuesta de ED 

### ISSUE THREAD

**Issue by alvarogaro** [marcosrmartin/PerroAndaluz#9]
* Buenas @marcosrmartin, he estado dándole unas vueltas al proyecto y había pensado en organizarlo de la siguiente manera:
## Clase Evento
* Basicamente va a representar el evento ( puede ser un viaje, compras...) en el cual vamos a realizar 
gastos y hay varios usuarios.
## Clase Usuario
* Representa a un usuario de la aplicación que va  a participar en uno o varios eventos.
## Clase Dinero
* Esta asociado a cada Usuario y a cada Evento. Tendremos una instancia de esta clase por usuario y por evento. En esta clase vamos a guardar tanto los gastos del usuario como la deuda que va acumulando en ese respectivo Evento.

* Echale un vistazo y dime que te parece o si has pensado organizarlo de alguna otra manera 🥶

**Comment by marcosrmartin** [comment]
Estoy de acuerdo con las 2 primeras clases, pero la clase dinero creo que podría ser simplemente un atributo en las clases que se requiera, además añadiría una clase *pago* la cual sería cada pago realizado dentro de un evento.

**Comment by alvarogaro** [comment]
Perfecto entonces voy a reestructurar las clases y me pongo al lio
